### ISSUE TITLE
Unable to customise filesSubDirectory on FSFilesAdapter

### ISSUE THREAD

**Issue by Kora3** [parse-community/parse-server-fs-adapter#49]
Hello how are you ?

I use this on parse server,

var fsAdapter = new FSFilesAdapter({
  "filesSubDirectory": "my/files/folder",
  "encryptionKey": "someKey"
});

var api = new ParseServer({
	appId: 'my_app',
	masterKey: 'master_key',
	filesAdapter: fsAdapter
})

When server start, FSFilesAdapter files is on files/my/files/folder instead of my/files/folder.

This may be due to this section of your code, line 180:

FileSystemAdapter.prototype._getApplicationDir = function() {
  if (this._filesDir) {
    return path.join('files', this._filesDir);
  } else {
    return 'files';
  }
 }

**Comment by mtrezza** [comment]
This is expected behavior for file upload to be confined to a parent directory.

I'm closing this as it does not use the issue template provided when creating an issue and therefore lacks essential information required to investigate the issue. Please edit your initial post using the issue template and we may re-open this issue.

**Comment by Kora3** [comment]
I see.

But this does not leave the possibility of storing the files on an external medium in the case where the parent directory is limited in terms of storage. Also, keeping the files directory in the same directory as parse server makes the directory bulkier and less organized.

It might be wiser to allow files to be stored in the directory of our choice depending on our configuration.

THANKS
